/* ===== ePitch Master — ผลบอลสด (live scores) =====
   Data: ESPN public site API (CORS *) — all soccer scoreboard, one request per ESPN (US-Eastern) date
         TheSportsDB free public test key "3" (CORS *) — Thai League 1/2 (not in ESPN's live feed)
   No private key is used. League id map regenerated by /workspace/update-epitch-leagues.py */
(function () {
  "use strict";
  var root = document.getElementById("liveScore");
  if (!root) return;

  var CFG = (window.EPM && window.EPM.scores) || { pinned: [], tsdb: [], leagues: {}, refreshMs: 45000 };
  var LEAGUES = CFG.leagues;

  var TZ = "Asia/Bangkok";
  var ESPN = "https://site.api.espn.com/apis/site/v2/sports/soccer/";
  var TSDB = "https://www.thesportsdb.com/api/v1/json/3/";
  var REFRESH_MS = CFG.refreshMs || 45000;

  /* pinned leagues (order = display priority) + Thai names */
  var PIN = CFG.pinned;
  var PIN_IDX = {}, TH_NAME = {};
  PIN.forEach(function (p, i) { PIN_IDX[p[0]] = i; TH_NAME[p[0]] = p[1]; });
  var TOP5 = { "eng.1": 1, "esp.1": 1, "ita.1": 1, "ger.1": 1, "fra.1": 1, "tsdb.4743": 1, "uefa.champions": 1, "uefa.europa": 1 };
  var TSDB_LEAGUES = CFG.tsdb;
  var COUNTRY = CFG.country || {};

  /* ---------- helpers ---------- */
  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  var fmtDay = new Intl.DateTimeFormat("en-CA", { timeZone: TZ, year: "numeric", month: "2-digit", day: "2-digit" });
  var fmtTime = new Intl.DateTimeFormat("th-TH", { timeZone: TZ, hour: "2-digit", minute: "2-digit", hour12: false });
  var fmtLong = new Intl.DateTimeFormat("th-TH", { timeZone: "UTC", weekday: "long", day: "numeric", month: "long", year: "numeric" });
  function bkkDay(d) { return fmtDay.format(d); }               /* YYYY-MM-DD in Bangkok */
  function addDays(ymd, n) { var p = ymd.split("-"); var t = new Date(Date.UTC(+p[0], +p[1] - 1, +p[2] + n)); return t.toISOString().slice(0, 10); }
  function compact(ymd) { return ymd.replace(/-/g, ""); }
  function longDate(ymd) { var p = ymd.split("-"); return fmtLong.format(new Date(Date.UTC(+p[0], +p[1] - 1, +p[2], 12))); }
  function hhmm(d) { return fmtTime.format(d); }
  function espnImg(url, w) {
    if (!url) return "";
    var m = url.match(/^https:\/\/a\.espncdn\.com(\/i\/[^?]+\.png)$/);
    return m ? "https://a.espncdn.com/combiner/i?img=" + m[1] + "&w=" + w + "&h=" + w : url;
  }
  function fetchJSON(url, ms) {
    var ctl = ("AbortController" in window) ? new AbortController() : null;
    var t = setTimeout(function () { if (ctl) ctl.abort(); }, ms || 15000);
    return fetch(url, { signal: ctl ? ctl.signal : undefined, cache: "no-store" }).then(function (r) {
      clearTimeout(t);
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    }, function (e) { clearTimeout(t); throw e; });
  }

  /* ---------- status ---------- */
  var LIVE_NAMES = { STATUS_FIRST_HALF: "ครึ่งแรก", STATUS_SECOND_HALF: "ครึ่งหลัง", STATUS_OVERTIME: "ต่อเวลาพิเศษ", STATUS_EXTRA_TIME: "ต่อเวลาพิเศษ",
    STATUS_FIRST_HALF_EXTRA_TIME: "ต่อเวลา ครึ่งแรก", STATUS_SECOND_HALF_EXTRA_TIME: "ต่อเวลา ครึ่งหลัง", STATUS_SHOOTOUT: "ดวลจุดโทษ", STATUS_IN_PROGRESS: "กำลังแข่ง" };
  var BREAK_NAMES = { STATUS_HALFTIME: "พักครึ่ง", STATUS_END_OF_REGULATION: "จบ 90 นาที", STATUS_HALFTIME_ET: "พักต่อเวลา", STATUS_END_OF_EXTRATIME: "จบต่อเวลา" };
  var POST_NAMES = { STATUS_FULL_TIME: "จบเกม", STATUS_FINAL: "จบเกม", STATUS_FINAL_AET: "จบเกม (ต่อเวลา)", STATUS_FINAL_PEN: "จบเกม (จุดโทษ)" };
  var OFF_NAMES = { STATUS_POSTPONED: "เลื่อน", STATUS_CANCELED: "ยกเลิก", STATUS_ABANDONED: "ยุติการแข่งขัน", STATUS_SUSPENDED: "หยุดชั่วคราว", STATUS_DELAYED: "ล่าช้า", STATUS_FORFEIT: "ปรับแพ้" };
  /* returns {k: live|break|post|pre|off, label, clock} */
  function statusOf(name, state, clock) {
    if (LIVE_NAMES[name]) return { k: "live", label: LIVE_NAMES[name], clock: clock || "" };
    if (BREAK_NAMES[name]) return { k: "break", label: BREAK_NAMES[name], clock: "" };
    if (POST_NAMES[name]) return { k: "post", label: POST_NAMES[name] };
    if (OFF_NAMES[name]) return { k: "off", label: OFF_NAMES[name] };
    if (state === "in") return { k: "live", label: "กำลังแข่ง", clock: clock || "" };
    if (state === "post") return { k: "post", label: "จบเกม" };
    return { k: "pre", label: "ยังไม่เตะ" };
  }
  function tsdbStatus(s, hs) {
    s = (s || "").toUpperCase();
    if (s === "1H") return { k: "live", label: "ครึ่งแรก", clock: "" };
    if (s === "2H") return { k: "live", label: "ครึ่งหลัง", clock: "" };
    if (s === "ET" || s === "P" || s === "LIVE" || s === "BT") return { k: "live", label: "กำลังแข่ง", clock: "" };
    if (s === "HT") return { k: "break", label: "พักครึ่ง" };
    if (s === "FT" || s === "MATCH FINISHED") return { k: "post", label: "จบเกม" };
    if (s === "AET") return { k: "post", label: "จบเกม (ต่อเวลา)" };
    if (s === "PEN") return { k: "post", label: "จบเกม (จุดโทษ)" };
    if (s === "PST" || s === "POSTPONED") return { k: "off", label: "เลื่อน" };
    if (s === "CANC" || s === "CANCELLED") return { k: "off", label: "ยกเลิก" };
    if (s === "ABD" || s === "ABANDONED") return { k: "off", label: "ยุติการแข่งขัน" };
    if (hs != null && hs !== "" && s !== "NS") return { k: "post", label: "จบเกม" };
    return { k: "pre", label: "ยังไม่เตะ" };
  }

  /* ---------- normalise ---------- */
  function lgInfo(id, ev) {
    var L = LEAGUES[id];
    if (L) return { key: L[0] || ("l" + id), en: L[1], logo: L[2] ? "https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/" + L[2] + ".png&w=56&h=56" : "" };
    var slug = "";
    (ev.links || []).some(function (l) { var m = /\/league\/([a-z0-9._]+)/.exec(l.href || ""); if (m) { slug = m[1]; return true; } });
    return { key: slug || ("l" + id), en: (ev.season && ev.season.slug ? ev.season.slug.replace(/-/g, " ") : "") || slug || "ลีกอื่น ๆ", logo: "" };
  }
  function evDetails(c) {
    return (c.details || []).filter(function (x) { return (x.scoringPlay && !x.shootout) || x.redCard; }).map(function (x) {
      var a = (x.athletesInvolved || [])[0] || {};
      return { team: x.team && x.team.id, name: a.shortName || a.displayName || "", min: (x.clock && x.clock.displayValue) || "",
        goal: !!x.scoringPlay, pen: !!x.penaltyKick, og: !!x.ownGoal, red: !!x.redCard };
    });
  }
  function fromEspn(ev) {
    var c = (ev.competitions || [])[0] || {};
    var lid = ((c.uid || ev.uid || "").match(/~l:(\d+)/) || [])[1] || "";
    var lg = lgInfo(lid, ev);
    var side = {};
    (c.competitors || []).forEach(function (t) {
      var tm = t.team || {};
      side[t.homeAway] = { id: tm.id, name: tm.displayName || tm.name || "?", short: tm.shortDisplayName || tm.displayName || "?",
        logo: espnImg(tm.logo, 48), score: t.score, so: t.shootoutScore, win: t.winner };
    });
    var st = ev.status || c.status || {}, ty = st.type || {};
    return { id: ev.id, src: "espn", lg: lg, t: new Date(ev.date), home: side.home || { name: "?" }, away: side.away || { name: "?" },
      st: statusOf(ty.name, ty.state, st.displayClock), det: evDetails(c), hasDet: !!(c.details && c.details.length) };
  }
  function fromTsdb(e, L) {
    var ts = e.strTimestamp ? new Date(e.strTimestamp.replace(" ", "T") + (/[zZ+]/.test(e.strTimestamp.slice(10)) ? "" : "Z")) : new Date(e.dateEvent + "T" + (e.strTime || "00:00:00") + "Z");
    var tiny = function (u) { return u ? u + "/tiny" : ""; };
    return { id: "ts" + e.idEvent, src: "tsdb", lg: { key: L.key, en: L.name, logo: L.logo || tiny(e.strLeagueBadge) }, t: ts,
      home: { name: e.strHomeTeam, short: e.strHomeTeam, logo: tiny(e.strHomeTeamBadge), score: e.intHomeScore },
      away: { name: e.strAwayTeam, short: e.strAwayTeam, logo: tiny(e.strAwayTeamBadge), score: e.intAwayScore },
      st: e.strPostponed === "yes" ? { k: "off", label: "เลื่อน" } : tsdbStatus(e.strStatus, e.intHomeScore), det: [], hasDet: false, noDet: true };
  }

  /* ---------- fetching (cache per source-day) ---------- */
  var cache = {};   /* key -> {at, events, err} */
  function getEspnDay(yyyymmdd, force) {
    var k = "e" + yyyymmdd, c = cache[k];
    if (c && !force && c.events) return Promise.resolve(c);
    return fetchJSON(ESPN + "all/scoreboard?dates=" + yyyymmdd + "&limit=1000", 20000).then(function (j) {
      cache[k] = { at: Date.now(), events: (j.events || []).map(fromEspn) }; return cache[k];
    }, function (err) { if (c && c.events) return c; throw err; });
  }
  function getTsdbDay(ymd, force) {
    var k = "t" + ymd, c = cache[k];
    if (c && !force && c.events) return Promise.resolve(c);
    /* free key: eventsday is capped (≈3 rows) so also merge last/next round results */
    var jobs = [];
    TSDB_LEAGUES.forEach(function (L) {
      jobs.push(fetchJSON(TSDB + "eventsday.php?d=" + ymd + "&l=" + L.id, 12000).then(function (j) { return { L: L, ev: j.events || [] }; }, function () { return { L: L, ev: [], fail: 1 }; }));
    });
    jobs.push(fetchJSON(TSDB + "eventspastleague.php?id=4743", 12000).then(function (j) { return { L: TSDB_LEAGUES[0], ev: j.events || [] }; }, function () { return { L: TSDB_LEAGUES[0], ev: [] }; }));
    jobs.push(fetchJSON(TSDB + "eventsnextleague.php?id=4743", 12000).then(function (j) { return { L: TSDB_LEAGUES[0], ev: j.events || [] }; }, function () { return { L: TSDB_LEAGUES[0], ev: [] }; }));
    return Promise.all(jobs).then(function (rs) {
      var seen = {}, out = [], fails = 0;
      rs.forEach(function (r) {
        if (r.fail) fails++;
        r.ev.forEach(function (e) { if (e.strSport && e.strSport !== "Soccer") return; if (seen[e.idEvent]) return; seen[e.idEvent] = 1; out.push(fromTsdb(e, r.L)); });
      });
      if (fails === TSDB_LEAGUES.length && !out.length) throw new Error("TheSportsDB unavailable");
      cache[k] = { at: Date.now(), events: out }; return cache[k];
    });
  }

  /* ---------- state ---------- */
  var S = { day: bkkDay(new Date()), filter: "all", view: "league", league: "", q: "", open: {}, exp: {}, more: 0, loading: true, err: "", warn: "", events: [], updated: null };
  var timer = null, started = false;

  function load(force) {
    var day = S.day, e1 = compact(addDays(day, -1)), e2 = compact(day);
    S.loading = true; S.err = ""; if (!S.events.length || force === "day") render();
    var espnJobs = [getEspnDay(e1, force === true), getEspnDay(e2, force === true)];
    var tsJob = getTsdbDay(day, force === true).then(function (c) { return c; }, function () { return { events: [], failed: true }; });
    return Promise.all([Promise.all(espnJobs).then(function (r) { return r; }, function (err) { return { error: err }; }), tsJob]).then(function (res) {
      if (day !== S.day) return;
      var espn = res[0], ts = res[1], all = [];
      S.loading = false; S.warn = "";
      if (espn.error) { S.err = "โหลดข้อมูลจาก ESPN ไม่สำเร็จ (" + (espn.error.name === "AbortError" ? "หมดเวลา" : esc(espn.error.message || "เครือข่าย")) + ")"; }
      else espn.forEach(function (c) { all = all.concat(c.events); });
      if (ts.failed) S.warn = "โหลดไทยลีกจาก TheSportsDB ไม่สำเร็จ";
      all = all.concat(ts.events || []);
      var seen = {};
      S.events = all.filter(function (m) { if (seen[m.id]) return false; seen[m.id] = 1; return bkkDay(m.t) === day; });
      S.updated = new Date();
      render(); schedule();
    });
  }
  function hasLiveOrSoon() {
    var now = Date.now();
    return S.events.some(function (m) { return m.st.k === "live" || m.st.k === "break" || (m.st.k === "pre" && m.t.getTime() - now < 10 * 60000 && now - m.t.getTime() < 3 * 3600000); });
  }
  function schedule() {
    clearTimeout(timer); timer = null;
    if (document.visibilityState !== "visible" || !hasLiveOrSoon()) return;
    timer = setTimeout(function () { load(true); }, REFRESH_MS);
  }
  document.addEventListener("visibilitychange", function () {
    if (!started) return;
    if (document.visibilityState === "visible") { if (S.updated && Date.now() - S.updated > REFRESH_MS && hasLiveOrSoon()) load(true); else schedule(); }
    else { clearTimeout(timer); timer = null; }
  });

  /* ---------- render ---------- */
  function lgName(lg) { return TH_NAME[lg.key] || lg.en; }
  function lgCountry(key) { return COUNTRY[String(key).split(".")[0]] || ""; }
  function isLive(m) { return m.st.k === "live" || m.st.k === "break"; }
  function groupSort(a, b) {
    var pa = PIN_IDX[a.key], pb = PIN_IDX[b.key];
    if (pa != null || pb != null) return (pa == null ? 999 : pa) - (pb == null ? 999 : pb);
    if (a.live !== b.live) return b.live - a.live;
    return a.en.localeCompare(b.en);
  }
  function crest(url, name, cls) {
    var ini = esc((name || "?").replace(/[^A-Za-z0-9\u0E00-\u0E7F ]/g, "").split(" ").filter(Boolean).map(function (w) { return w[0]; }).join("").slice(0, 2).toUpperCase() || "⚽");
    return '<span class="' + cls + '" data-ini="' + ini + '">' + (url ? '<img src="' + esc(url) + '" alt="" loading="lazy" decoding="async" onerror="this.remove()">' : "") + "</span>";
  }
  /* centre column: score (or kickoff time) + status badge */
  function centre(m) {
    var s = m.st, sc = function (t) { return t.score != null && t.score !== "" ? esc(t.score) : "–"; };
    var showScore = s.k === "live" || s.k === "break" || s.k === "post" || (s.k === "off" && m.home.score != null && m.home.score !== "" && m.home.score !== "0");
    var mid = showScore
      ? '<span class="ls-score">' + sc(m.home) + '<i>-</i>' + sc(m.away) + "</span>" +
        (m.home.so != null && m.away.so != null ? '<span class="ls-pens">จุดโทษ ' + esc(m.home.so) + "-" + esc(m.away.so) + "</span>" : "")
      : '<span class="ls-ko">' + hhmm(m.t) + "</span>";
    var b;
    if (s.k === "live") b = '<span class="ls-badge live"><i></i>' + (s.clock ? esc(s.clock) : "LIVE") + "</span>";
    else if (s.k === "break") b = '<span class="ls-badge brk">' + esc(s.label) + "</span>";
    else if (s.k === "post") b = '<span class="ls-badge ft">' + (s.label === "จบเกม" ? "จบ" : esc(s.label.replace("จบเกม ", "จบ "))) + "</span>";
    else if (s.k === "off") b = '<span class="ls-badge off">' + esc(s.label) + "</span>";
    else b = '<span class="ls-badge pre">ยังไม่เตะ</span>';
    return '<div class="ls-mid">' + mid + b + "</div>";
  }
  function sideEvents(m, side) {
    var tid = m[side].id, out = [];
    m.det.forEach(function (d) {
      if (d.team !== tid) return;
      out.push('<li class="' + (d.red ? "red" : "goal") + '"><span class="ls-evi" aria-hidden="true">' + (d.red ? '<i class="ls-rc"></i>' : "⚽") + "</span>" +
        '<span class="ls-evn">' + esc(d.name || "ไม่ระบุชื่อ") + "</span><b>" + esc(d.min) + "</b>" +
        (d.pen ? '<em class="ls-tag" title="ยิงจุดโทษ">P</em>' : "") + (d.og ? '<em class="ls-tag og" title="ทำเข้าประตูตัวเอง">OG</em>' : "") + "</li>");
    });
    return '<ul class="ls-evl ' + side + '">' + (out.join("") || '<li class="none">—</li>') + "</ul>";
  }
  function canExpand(m) { return m.st.k !== "pre" && (m.det.length || m.src === "espn" || m.noDet); }
  function goalsTotal(m) { return (+m.home.score || 0) + (+m.away.score || 0); }
  function detailHTML(m) {
    var body;
    if (m.noDet) body = '<p class="ls-dnote">แหล่งข้อมูลไทยลีก (TheSportsDB รุ่นฟรี) ไม่มีรายชื่อผู้ทำประตู</p>';
    else if (m.det.length) body = '<div class="ls-dcols">' + sideEvents(m, "home") + sideEvents(m, "away") + "</div>";
    else if (m.lazyMsg) body = '<p class="ls-dnote">' + esc(m.lazyMsg) + "</p>";
    else if (m.src === "espn" && !m.hasDet && !m.lazy && goalsTotal(m) > 0) body = '<p class="ls-dnote">กำลังโหลดผู้ทำประตู…</p>';
    else body = '<p class="ls-dnote">' + (goalsTotal(m) ? "ยังไม่มีรายชื่อผู้ทำประตู" : "ยังไม่มีประตูหรือใบแดง") + "</p>";
    return '<div class="ls-detail">' + body + "</div>";
  }
  function redCount(m, side) { var tid = m[side].id; return m.det.filter(function (d) { return d.red && d.team === tid; }).length; }
  function teamCell(m, side) {
    var t = m[side], lose = m.st.k === "post" && m.home.score !== m.away.score && t.win === false, rc = redCount(m, side);
    return '<span class="ls-side ' + side + (lose ? " lose" : "") + '">' + crest(t.logo, t.name, "ls-crest") +
      '<span class="ls-tn" title="' + esc(t.name) + '">' + esc(t.short || t.name) + "</span>" +
      (rc ? '<i class="ls-rc" title="ใบแดง ' + rc + '"></i>' : "") + "</span>";
  }
  function matchRow(m, ctx) {
    var ex = canExpand(m), open = ex && !!S.exp[m.id];
    var sub = ctx ? '<span class="ls-ctx">' + crest(m.lg.logo, m.lg.en, "ls-lc") + esc(lgName(m.lg)) + "</span>" : "";
    return '<div class="ls-match ' + m.st.k + (open ? " open" : "") + '" data-id="' + esc(m.id) + '">' + sub +
      (ex ? '<button class="ls-row" type="button" aria-expanded="' + open + '" data-x="' + esc(m.id) + '">' : '<div class="ls-row">') +
      teamCell(m, "home") + centre(m) + teamCell(m, "away") +
      (ex ? '<span class="ls-chev" aria-hidden="true"></span></button>' : "</div>") +
      (open ? detailHTML(m) : "") + "</div>";
  }
  function matchesFilter(m) {
    if (S.filter === "live" && !isLive(m)) return false;
    if (S.filter === "pop" && PIN_IDX[m.lg.key] == null) return false;
    if (S.filter === "ft" && m.st.k !== "post") return false;
    if (S.filter === "pre" && m.st.k !== "pre") return false;
    if (S.league && m.lg.key !== S.league) return false;
    if (S.q) {
      var hay = (m.home.name + " " + m.away.name + " " + m.lg.en + " " + lgName(m.lg)).toLowerCase();
      if (hay.indexOf(S.q) < 0) return false;
    }
    return true;
  }
  function buildGroups(list) {
    var g = {}, arr = [];
    list.forEach(function (m) {
      var k = m.lg.key;
      if (!g[k]) { g[k] = { key: k, en: m.lg.en, logo: m.lg.logo, ms: [], live: 0 }; arr.push(g[k]); }
      g[k].ms.push(m); if (isLive(m)) g[k].live++;
      if (!g[k].logo && m.lg.logo) g[k].logo = m.lg.logo;
    });
    arr.forEach(function (x) { x.ms.sort(function (a, b) { return a.t - b.t || a.home.name.localeCompare(b.home.name); }); });
    return arr.sort(groupSort);
  }
  function isOpen(gr) {
    if (S.open[gr.key] != null) return S.open[gr.key];
    return PIN_IDX[gr.key] != null || !!gr.live || !!S.league || !!S.q || S.filter === "live";
  }
  function leagueView(list) {
    return buildGroups(list).map(function (gr) {
      var open = isOpen(gr), th = TH_NAME[gr.key], cty = lgCountry(gr.key);
      return '<section class="ls-group' + (open ? " open" : "") + '" data-g="' + esc(gr.key) + '">' +
        '<button class="ls-ghead" type="button" aria-expanded="' + open + '">' + crest(gr.logo, gr.en, "ls-glogo") +
        '<span class="ls-gname"><b>' + esc(th || gr.en) + "</b><small>" + esc([cty, th ? gr.en : ""].filter(Boolean).join(" · ") || "ฟุตบอล") + "</small></span>" +
        (gr.live ? '<span class="ls-gl"><i></i>' + gr.live + "</span>" : "") + '<span class="ls-gc">' + gr.ms.length + '</span><span class="ls-gchev" aria-hidden="true"></span></button>' +
        (open ? '<div class="ls-gbody">' + gr.ms.map(function (m) { return matchRow(m, false); }).join("") + "</div>" : "") + "</section>";
    }).join("");
  }
  var TEAM_PAGE = 40;
  function teamView(list) {
    var rows = [];
    list.forEach(function (m) { rows.push({ t: m.home, m: m }); rows.push({ t: m.away, m: m }); });
    var lq = S.q;
    if (lq) rows = rows.filter(function (r) { return r.t.name.toLowerCase().indexOf(lq) >= 0 || lgName(r.m.lg).toLowerCase().indexOf(lq) >= 0 || r.m.lg.en.toLowerCase().indexOf(lq) >= 0; });
    rows.sort(function (a, b) { return (isLive(b.m) - isLive(a.m)) || a.t.name.localeCompare(b.t.name); });
    var lim = TEAM_PAGE * (S.more + 1), shown = rows.slice(0, lim), lastL = "";
    var h = shown.map(function (r) {
      var L = isLive(r.m) ? "LIVE" : (r.t.name.charAt(0).toUpperCase() || "#");
      var hd = L !== lastL ? '<h4 class="ls-letter">' + (L === "LIVE" ? '<i class="dotl"></i>กำลังแข่ง' : esc(L)) + "</h4>" : ""; lastL = L;
      return hd + '<section class="ls-group ls-tgroup open"><div class="ls-thead">' + crest(r.t.logo, r.t.name, "ls-glogo") +
        '<span class="ls-gname"><b>' + esc(r.t.name) + "</b><small>" + esc(lgName(r.m.lg)) + "</small></span></div>" +
        '<div class="ls-gbody">' + matchRow(r.m, false) + "</div></section>";
    }).join("");
    if (rows.length > lim) h += '<button class="ls-loadmore" type="button">แสดงเพิ่ม (' + (rows.length - lim) + " ทีม)</button>";
    return h;
  }

  var els = {};
  function render() {
    var today = bkkDay(new Date());
    els.days.forEach(function (b) { var d = addDays(today, +b.getAttribute("data-day")); b.setAttribute("aria-pressed", String(d === S.day)); });
    var dayIdx = [-1, 0, 1].map(function (n) { return addDays(today, n); }).indexOf(S.day);
    els.seg.setAttribute("data-active", String(dayIdx));
    els.date.value = S.day;
    els.calTxt.textContent = shortDate(S.day);
    els.cal.classList.toggle("on", dayIdx < 0);
    els.dateLabel.textContent = longDate(S.day) + (S.day === today ? " · วันนี้" : "");
    var cnt = { all: S.events.length, live: 0, ft: 0, pre: 0, pop: 0 };
    S.events.forEach(function (m) { if (isLive(m)) cnt.live++; if (m.st.k === "post") cnt.ft++; if (m.st.k === "pre") cnt.pre++; if (PIN_IDX[m.lg.key] != null) cnt.pop++; });
    $all(".ls-fchip", els.filters).forEach(function (b) {
      var f = b.getAttribute("data-f"); b.setAttribute("aria-pressed", String(f === S.filter));
      var c = b.querySelector("small"); if (c) c.textContent = S.events.length ? cnt[f] : "";
    });
    $all(".ls-vbtn", root).forEach(function (b) { b.setAttribute("aria-pressed", String(b.getAttribute("data-v") === S.view)); });
    els.vseg.setAttribute("data-active", S.view === "team" ? "1" : "0");

    if (S.loading && !S.events.length) {
      els.list.innerHTML = '<div class="ls-skel">' + new Array(5).join('<div class="ls-sk"><span></span><span></span><span></span></div>') + '</div><p class="ls-status">กำลังโหลดโปรแกรมและผลบอล…</p>';
      els.meta.innerHTML = ""; els.leagues.innerHTML = "";
      return;
    }
    if (S.err && !S.events.length) {
      els.list.innerHTML = '<div class="ls-error"><b>⚠️ ' + S.err + '</b><p>อาจเป็นเพราะอินเทอร์เน็ตหลุดหรือแหล่งข้อมูลขัดข้องชั่วคราว</p><button class="btn btn-neon ls-retry" type="button">ลองอีกครั้ง ↻</button></div>';
      els.meta.innerHTML = ""; els.leagues.innerHTML = "";
      return;
    }
    var allGroups = buildGroups(S.events);
    els.meta.innerHTML = "<span><b>" + S.events.length + "</b> คู่ · <b>" + allGroups.length + "</b> รายการ</span>" +
      (S.updated ? '<span class="ls-upd">อัปเดต ' + hhmm(S.updated) + " น." + (S.loading ? " · กำลังรีเฟรช…" : (timer ? " · รีเฟรชอัตโนมัติ" : "")) + "</span>" : "") +
      '<button class="ls-refresh" type="button" aria-label="รีเฟรช" title="รีเฟรช">↻</button>';
    els.leagues.innerHTML = '<button class="ls-lchip" type="button" data-lg="" aria-pressed="' + String(!S.league) + '"><span class="ls-lc all" aria-hidden="true">🌐</span>ทุกลีก <small>' + S.events.length + "</small></button>" + allGroups.map(function (gr) {
      return '<button class="ls-lchip" type="button" data-lg="' + esc(gr.key) + '" aria-pressed="' + String(S.league === gr.key) + '">' +
        crest(gr.logo, gr.en, "ls-lc") + '<span class="ls-lcn">' + esc(lgName(gr)) + "</span> <small>" + gr.ms.length + "</small></button>";
    }).join("");

    var list = S.events.filter(S.view === "team" ? function (m) { var q = S.q; S.q = ""; var ok = matchesFilter(m); S.q = q; return ok; } : matchesFilter);
    var warn = (S.warn ? '<p class="ls-warn">⚠️ ' + esc(S.warn) + "</p>" : "") + (S.err ? '<p class="ls-warn">⚠️ ' + S.err + "</p>" : "");
    var body = list.length ? (S.view === "team" ? teamView(list) : leagueView(list)) : "";
    if (!body) {
      els.list.innerHTML = warn + '<div class="ls-empty">' + (S.events.length ? "ไม่พบคู่ที่ตรงกับตัวกรอง/คำค้นหา" : "ไม่มีโปรแกรมการแข่งขันในวันนี้จากแหล่งข้อมูล") + "</div>";
      return;
    }
    els.list.innerHTML = warn + body;
  }
  function $all(sel, el) { return Array.prototype.slice.call((el || document).querySelectorAll(sel)); }
  var fmtShort = new Intl.DateTimeFormat("th-TH", { timeZone: "UTC", day: "numeric", month: "short" });
  function shortDate(ymd) { var p = ymd.split("-"); return fmtShort.format(new Date(Date.UTC(+p[0], +p[1] - 1, +p[2], 12))); }

  /* lazy summary fetch for matches whose scoreboard row has no scorer details */
  function loadMore(id) {
    var m = S.events.filter(function (x) { return x.id === id; })[0];
    if (!m || m.lazy || m.loadingDet) return;
    m.loadingDet = true;
    fetchJSON(ESPN + "all/summary?event=" + encodeURIComponent(id), 15000).then(function (j) {
      var det = [];
      (j.keyEvents || []).forEach(function (k) {
        var txt = (k.type && k.type.text) || "", red = /red card/i.test(txt), goal = !!k.scoringPlay || /goal|penalty - scored/i.test(txt);
        if (/shootout/i.test(txt) || k.shootout) return;
        if (!(goal || red)) return;
        var p = ((k.participants || [])[0] || {}).athlete || {};
        det.push({ team: k.team && k.team.id, name: p.shortName || p.displayName || "", min: (k.clock && k.clock.displayValue) || "",
          goal: goal && !red, pen: /penalty/i.test(txt), og: /own goal/i.test(txt), red: red });
      });
      m.det = det; m.lazy = true; m.loadingDet = false; m.lazyMsg = det.length ? "" : "แหล่งข้อมูลยังไม่มีรายชื่อผู้ทำประตูของคู่นี้";
      render();
    }, function () { m.loadingDet = false; m.lazyMsg = "โหลดรายชื่อผู้ทำประตูไม่สำเร็จ แตะอีกครั้งเพื่อลองใหม่"; render(); m.lazyMsg = ""; });
  }

  /* ---------- build UI ---------- */
  root.innerHTML =
    '<div class="ls-bar">' +
      '<div class="ls-dayrow">' +
        '<div class="ls-seg" role="group" aria-label="เลือกวัน" data-active="1"><span class="ls-glider" aria-hidden="true"></span>' +
          '<button class="ls-day" type="button" data-day="-1">เมื่อวาน</button>' +
          '<button class="ls-day" type="button" data-day="0">วันนี้</button>' +
          '<button class="ls-day" type="button" data-day="1">พรุ่งนี้</button>' +
        "</div>" +
        '<label class="ls-cal" title="เลือกวันจากปฏิทิน"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="5" width="17" height="15.5" rx="3"/><path d="M3.5 10h17M8 3v4M16 3v4"/></svg>' +
          '<span class="ls-caltxt"></span><input type="date" id="lsDate" aria-label="เลือกวันที่จากปฏิทิน"></label>' +
      "</div>" +
      '<p class="ls-dlabel" id="lsDateLabel"></p>' +
      '<div class="ls-filters" role="group" aria-label="ตัวกรอง">' +
        '<button class="ls-fchip" type="button" data-f="all">ทั้งหมด<small></small></button>' +
        '<button class="ls-fchip" type="button" data-f="live"><i class="dot"></i>กำลังแข่ง<small></small></button>' +
        '<button class="ls-fchip" type="button" data-f="pop">⭐ ยอดนิยม<small></small></button>' +
        '<button class="ls-fchip" type="button" data-f="pre">ยังไม่เตะ<small></small></button>' +
        '<button class="ls-fchip" type="button" data-f="ft">จบแล้ว<small></small></button>' +
      "</div>" +
      '<div class="ls-tools"><label class="ls-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="M15.5 15.5 21 21"/></svg>' +
        '<input type="search" id="lsSearch" placeholder="ค้นหาทีมหรือลีก" autocomplete="off" enterkeyhint="search" aria-label="ค้นหาทีมหรือลีก"></label>' +
        '<div class="ls-vseg" role="group" aria-label="มุมมอง" data-active="0"><span class="ls-glider" aria-hidden="true"></span>' +
          '<button class="ls-vbtn" type="button" data-v="league">ตามลีก</button><button class="ls-vbtn" type="button" data-v="team">ตามทีม</button></div>' +
      "</div>" +
    "</div>" +
    '<div class="ls-leagues" id="lsLeagues" aria-label="เลือกลีก"></div>' +
    '<div class="ls-meta" id="lsMeta" aria-live="polite"></div>' +
    '<div class="ls-list" id="lsList"></div>' +
    '<p class="ls-src">📡 ข้อมูลจาก <a href="https://www.espn.com/soccer/scoreboard" target="_blank" rel="noopener">ESPN</a> (ฟีดสาธารณะ) และ <a href="https://www.thesportsdb.com/" target="_blank" rel="noopener">TheSportsDB</a> สำหรับไทยลีก · เวลาประเทศไทย · ' +
    "ผลอาจช้ากว่าจริงประมาณ 1–2 นาที ไทยลีกอัปเดตช้ากว่าและไม่มีรายชื่อผู้ทำประตู · แตะคู่แข่งขันเพื่อดูผู้ทำประตู · P = จุดโทษ, OG = ทำเข้าประตูตัวเอง, <i class=\"ls-rc\"></i> = ใบแดง · ไม่ใช่ข้อมูลทางการของลีก</p>";
  els.days = $all(".ls-day", root);
  els.seg = root.querySelector(".ls-seg");
  els.vseg = root.querySelector(".ls-vseg");
  els.cal = root.querySelector(".ls-cal");
  els.calTxt = root.querySelector(".ls-caltxt");
  els.date = root.querySelector("#lsDate");
  els.dateLabel = root.querySelector("#lsDateLabel");
  els.filters = root.querySelector(".ls-filters");
  els.leagues = root.querySelector("#lsLeagues");
  els.meta = root.querySelector("#lsMeta");
  els.list = root.querySelector("#lsList");
  var search = root.querySelector("#lsSearch");

  function setDay(d) { if (!d || d === S.day) return; S.day = d; S.events = []; S.league = ""; S.open = {}; S.exp = {}; S.more = 0; S.updated = null; clearTimeout(timer); timer = null; load("day"); }
  els.days.forEach(function (b) { b.addEventListener("click", function () { setDay(addDays(bkkDay(new Date()), +b.getAttribute("data-day"))); }); });
  els.date.addEventListener("change", function () { if (/^\d{4}-\d{2}-\d{2}$/.test(els.date.value)) setDay(els.date.value); });
  els.date.addEventListener("click", function () { try { if (els.date.showPicker) els.date.showPicker(); } catch (e) {} });
  els.filters.addEventListener("click", function (e) { var b = e.target.closest(".ls-fchip"); if (!b) return; S.filter = b.getAttribute("data-f"); S.more = 0; render(); });
  els.leagues.addEventListener("click", function (e) {
    var b = e.target.closest(".ls-lchip"); if (!b) return; S.league = b.getAttribute("data-lg"); S.more = 0; render();
    var on = els.leagues.querySelector('[aria-pressed="true"]'); if (on && on.scrollIntoView) on.scrollIntoView({ block: "nearest", inline: "center" });
  });
  var qT; search.addEventListener("input", function () { clearTimeout(qT); qT = setTimeout(function () { S.q = search.value.trim().toLowerCase(); S.more = 0; render(); }, 180); });
  root.addEventListener("click", function (e) {
    var v = e.target.closest(".ls-vbtn"); if (v) { S.view = v.getAttribute("data-v"); S.more = 0; render(); return; }
    var h = e.target.closest(".ls-ghead");
    if (h) { var g = h.parentNode.getAttribute("data-g"), gr = buildGroups(S.events.filter(function (m) { return m.lg.key === g; }))[0]; S.open[g] = !(gr && isOpen(gr)); render(); return; }
    var x = e.target.closest(".ls-row[data-x]");
    if (x) {
      var id = x.getAttribute("data-x"); S.exp[id] = !S.exp[id];
      var m = S.events.filter(function (y) { return y.id === id; })[0];
      if (S.exp[id] && m && m.src === "espn" && !m.hasDet && !m.lazy && goalsTotal(m) > 0) loadMore(id);
      render(); return;
    }
    if (e.target.closest(".ls-loadmore")) { S.more++; render(); return; }
    if (e.target.closest(".ls-refresh")) { load(true); return; }
    if (e.target.closest(".ls-retry")) { load(true); }
  });

  function start() { if (started) return; started = true; load(false); }
  render();
  start();
})();
